# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:  
    docker:
      - image: circleci/openjdk:8-jdk-stretch-browsers
         
    
    working_directory : ~/selenium-java

    steps:
      - checkout
      
      - run: mkdir test-reports
      
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true

      - run: cd GoogleSearch && mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "GoogleSearch/pom.xml" }}

      # run tests!
      - run: cd GoogleSearch && mvn clean integration-test
      
      - run:
          name: Save test results
          command: |
            mkdir -p ~/testng/results/
            find . -type f -regex "./GoogleSearch/test-output/emailable-report.html" -exec cp {} ~/testng/results/ \;
          when: always
      - store_test_results:
          path: ~/testng/results/
      - store_artifacts:
          path: ~/testng/results/